spring:
  application:
    name: tonpad
  sql:
    init:
      mode: never

app:
  data-path: "basePath"
  reserved-names:
    templates-dir: "templates"
    notes-dir: "notes"
  changelog-path: db/changelog/schema.sql
  validate-db-schema-path: db/validate_db_schema.sql